[project]
name = "private-pgm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "disjoint-set",
    "matplotlib",
    "networkx",
    "numpy",
    "pandas",
    "scipy",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mbi"]

[tool.hatch.metadata]
allow-direct-references = true

[dependency-groups]
dev = [
    "nose>=1.3.7",
]
